version: "3.9"

services:
  postgres_csv_import:
    image: postgres:15
    container_name: postgres_csv_import
    restart: unless-stopped
    environment:
      POSTGRES_DB: csv_import_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_csv_import_data:/var/lib/postgresql/data
    networks:
      - smart_network

  postgres_stock:
    image: postgres:15
    container_name: postgres_stock
    restart: unless-stopped
    environment:
      POSTGRES_DB: stock_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_stock_data:/var/lib/postgresql/data
    networks:
      - smart_network

  postgres_inference:
    image: postgres:15
    container_name: postgres_inference
    restart: unless-stopped
    environment:
      POSTGRES_DB: inference_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_inference_data:/var/lib/postgresql/data
    networks:
      - smart_network

  postgres_auth:
    image: postgres:15
    container_name: postgres_auth
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - smart_network

  postgres_alerts:
    image: postgres:15
    container_name: postgres_alerts
    restart: unless-stopped
    environment:
      POSTGRES_DB: alerts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - postgres_alerts_data:/var/lib/postgresql/data
    networks:
      - smart_network

  csv_import_service:
    build:
      context: ./services/csv_import_service
    container_name: csv_import_service
    restart: unless-stopped
    depends_on:
      - postgres_csv_import
      - stock_service
      - inference_service
    environment:
      DB_HOST: postgres_csv_import
      DB_PORT: 5432
      DB_NAME: csv_import_db
      DB_USER: postgres
      DB_PASS: postgres
      STOCK_SERVICE_URL: http://stock_service:2004
      INFERENCE_SERVICE_URL: http://inference_service:8020
    ports:
      - "8030:8030"
    networks:
      - smart_network

  stock_service:
    build:
      context: ./services/stock_service
    container_name: stock_service
    restart: unless-stopped
    depends_on:
      - postgres_stock
    environment:
      DB_HOST: postgres_stock
      DB_PORT: 5432
      DB_NAME: stock_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "2004:2004"
    networks:
      - smart_network

  inference_service:
    build:
      context: ./services/inference_service
    container_name: inference_service
    restart: unless-stopped
    depends_on:
      - postgres_inference
      - stock_service
    environment:
      DB_HOST: postgres_inference
      DB_PORT: 5432
      DB_NAME: inference_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      STOCK_SERVICE_URL: http://stock_service:2004
      DEFAULT_STORE_ID: STORE_Nord
      DEFAULT_REGION: UNKNOWN
    ports:
      - "8020:8020"
    networks:
      - smart_network

  auth_service:
    build:
      context: ./services/auth_service
    container_name: auth_service
    restart: unless-stopped
    depends_on:
      - postgres_auth
    env_file:
      - ./services/auth_service/.env
    ports:
      - "8007:8007"
    networks:
      - smart_network

  scraping_service:
    build:
      context: ./services/scraping_service
    container_name: scraping_service
    restart: unless-stopped
    depends_on:
      - stock_service
    environment:
      STOCK_SERVICE_URL: http://stock_service:2004
      SCRAPING_INTERVAL_MINUTES: 60
      HEADLESS: "true"
      REQUEST_TIMEOUT: 20
      MAX_PAGES_PER_CATALOG: 20
      USER_AGENT: Mozilla/5.0
    ports:
      - "8060:8060"
    networks:
      - smart_network


  alerts_service:
    build:
      context: ./services/alerts_service
    container_name: alerts_service
    restart: unless-stopped
    ports:
      - "8006:8006"
    environment:
      ALERTS_DATABASE_URL: postgresql://postgres:postgres@postgres_alerts:5432/alerts_db
      STOCK_DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres_stock:5432/stock_db
    depends_on:
      - postgres_alerts
    networks:
      - smart_network


  api_gateway:
    build:
      context: ./api_gateway
    container_name: api_gateway
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      AUTH_SERVICE_URL: http://auth_service:8007
      STOCK_SERVICE_URL: http://stock_service:2004
      ML_SERVICE_URL: http://inference_service:8020
      SCRAPING_SERVICE_URL: http://scraping_service:8060
      CSV_IMPORT_SERVICE_URL: http://csv_import_service:8030
      ALERTS_SERVICE_URL: http://alerts_service:8006
      FRONTEND_URL: http://localhost:5173
      DEFAULT_TIMEOUT_SECONDS: 120
      LONG_TIMEOUT_SECONDS: 600
    depends_on:
      - auth_service
      - stock_service
      - inference_service
      - scraping_service
      - csv_import_service
    networks:
      - smart_network    
      
volumes:
  postgres_csv_import_data:
  postgres_stock_data:
  postgres_inference_data:
  postgres_auth_data:
  postgres_alerts_data:

networks:
  smart_network:
    driver: bridge